-- ############################################################################
-- SYLVA  ·  PostgreSQL 16 + PostGIS 3.4  ·  complete schema
-- ############################################################################
--
-- HOW TO RUN
--   psql -v ON_ERROR_STOP=1 -f sylva.sql
--   The CREATE EXTENSION and CREATE ROLE statements at the top need a superuser.
--   Everything after `SET ROLE sylva_owner` is created BY sylva_owner, so
--   sylva_owner owns every object and FORCE ROW LEVEL SECURITY genuinely binds
--   it. In production the migration job connects as sylva_login_migrate.
--
-- VALIDATION STATUS (PostgreSQL 16.4, this machine)
--   The whole file applies with zero errors: 77 tables, 390 constraints,
--   215 row-level-security policies, 120 triggers, 0 float columns.
--   113 behavioural assertions pass against a LIVE multi-connection server,
--   including R1 under two real concurrent transactions, the full role-by-role
--   RLS matrix, temporal disclosure, and erasure.
--   17 further tests deliberately violate each CI assertion to prove the
--   assertion itself fails the build.
--   NOT VERIFIED HERE: every PostGIS expression. This machine has no PostGIS, so
--   geometry(MultiPolygon,4326) / geometry(Point,4326), ST_IsValid, ST_NPoints,
--   ST_Distance, ST_AsGeoJSON and the geography GiST indexes were exercised with
--   a bytea stand-in. They are standard, but run them once on the real cluster.
--   NOTE FOR WHOEVER WRITES THE TESTS: `postgres --single` silently does NOT
--   apply row-level security, so any RLS test run in single-user mode passes
--   vacuously. Every RLS test must run against a real server.
--
-- LOCAL DEVELOPMENT (no Docker, no psql on this machine)
--   sudo apt install postgresql-18 postgresql-18-postgis-3 postgresql-client-18
--   (18 satisfies "16+" and also supplies the missing psql.) Nothing in this
--   schema is newer than PostgreSQL 12 except num_nulls/num_nonnulls (9.6), so
--   it is 16-compatible. PIN CI TO WHATEVER MAJOR VERSION PRODUCTION WILL RUN -
--   that is the same question as which named EU member-state region to use.
--
-- WHAT IS NOT HERE, ON PURPOSE
--   No payments, escrow or settlement. No registry: Sylva stores references to
--   a scheme's records plus the supporting documents. No automatic legal or
--   environmental claim. No public comment feed. No conversion factor, no
--   equivalence table, no CO2e column, no exchange rate between unit types.
--   No cross-project totals view and no totals endpoint.
--
-- ############################################################################

-- ============================================================================
-- SYLVA  ·  PostgreSQL 16 + PostGIS 3.4
-- SECTION A · MVP
