#!/usr/bin/env tsx
/**
 * Write placeholder files for the SEEDED demo documents.
 *
 * The seeds create doc.document_version rows pointing at storage keys, because
 * a document's metadata is what the platform actually reasons about. They do
 * not create the bytes, so every seeded document's View and Download link
 * failed with "stored object absent" while documents uploaded through the
 * interface worked. Metadata without bytes is a half-built document; this
 * closes it.
 *
 * Each file is a real, openable PDF that says on its face what it is and that
 * it is demo data, so nobody can mistake a placeholder for a project document.
 *
 *   npx tsx scripts/make-demo-documents.ts
 */
import { mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname, join, resolve } from 'node:path';
import { Client } from 'pg';
import { config } from 'dotenv';

config({ path: '.env.local', quiet: true });

const ROOT = resolve(process.env.SYLVA_STORAGE_LOCAL_DIR ?? './.storage');

/** A minimal, valid, single-page PDF. No dependency, opens everywhere. */
function pdf(lines: string[]): Buffer {
  const esc = (s: string) => s.replace(/([()\\])/g, '\\$1');
  const body = lines
    .map((l, i) => `BT /F1 ${i === 0 ? 15 : 10} Tf 56 ${740 - i * 22} Td (${esc(l)}) Tj ET`)
    .join('\n');
  const objs = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>',
    `<< /Length ${body.length} >>\nstream\n${body}\nendstream`,
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
  ];
  let out = '%PDF-1.4\n';
  const offsets: number[] = [];
  objs.forEach((o, i) => {
    offsets.push(out.length);
    out += `${i + 1} 0 obj\n${o}\nendobj\n`;
  });
  const xref = out.length;
  out += `xref\n0 ${objs.length + 1}\n0000000000 65535 f \n`;
  for (const o of offsets) out += `${String(o).padStart(10, '0')} 00000 n \n`;
  out += `trailer\n<< /Size ${objs.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;
  return Buffer.from(out, 'latin1');
}

async function main(): Promise<void> {
const db = new Client({
  host: process.env.PGHOST, port: Number(process.env.PGPORT),
  user: process.env.PGUSER ?? 'postgres', database: process.env.PGDATABASE,
});
await db.connect();

const { rows } = await db.query<{
  storage_bucket: string; storage_key: string; kind: string;
  slug: string | null; version_no: number; media_type: string;
}>(`
  SELECT v.storage_bucket, v.storage_key, d.kind, p.slug, v.version_no, v.media_type
    FROM doc.document_version v
    JOIN doc.document d ON d.id = v.document_id
    LEFT JOIN proj.project p ON p.id = d.project_id
   WHERE v.storage_key LIKE 'demo/%'
   ORDER BY v.storage_key`);

let written = 0, already = 0;
for (const r of rows) {
  const path = join(ROOT, r.storage_bucket, r.storage_key);
  if (existsSync(path)) { already++; continue; }
  mkdirSync(dirname(path), { recursive: true });
  const bytes = pdf([
    'DEMONSTRATION DOCUMENT - NOT A REAL PROJECT DOCUMENT',
    '',
    `Document type : ${r.kind.replace(/_/g, ' ')}`,
    `Project       : ${r.slug ?? '(not attached to a project)'}`,
    `Version       : ${r.version_no}`,
    '',
    'This file is a placeholder generated by',
    'scripts/make-demo-documents.ts so that the demo data has real',
    'bytes behind it and every View and Download link works.',
    '',
    'It describes no real wetland, no real verification and no real',
    'environmental result. Replace it with the genuine document',
    'before this platform is shown as anything other than a demo.',
  ]);
  writeFileSync(path, bytes);
  written++;
}

await db.end();
console.log(`demo documents: ${written} written, ${already} already present, ${rows.length} total`);
if (rows.length === 0) console.log('  (no seeded documents found - run the seeds first)');
}

main().catch((err) => { console.error(err); process.exit(1); });
